from django.conf.urls.defaults import *
from j_nid.app import views

urlpatterns = patterns('',
    url(r'^banknames/$', views.get_banks),
    url(r'^bankaccounts/$', views.BankAccountController()),
    url(r'^sessions/$', views.SessionController()),
    url(r'^orders/$', views.OrderController()),
    url(r'^orders/(?P<id>\d+)/$', views.OrderController(), name='jn_order_detail'),
    url(r'^orderitems/$', views.OrderItemController()),
    url(r'^orderitems/(?P<id>\d+)/$', views.OrderItemController()),
	url(r'^supplies/$', views.SupplyController()),
    url(r'^supplies/(?P<id>\d+)/$', views.SupplyController()),
    url(r'^supplyitems/$', views.SupplyItemController()),
    url(r'^supplyitems/(?P<id>\d+)/$', views.SupplyItemController()),
    url(r'^payments/$', views.PaymentController()),
    url(r'^payments/(?P<id>\d+)/$', views.PaymentController()),
    url(r'^people/$', views.PersonController()),
    url(r'^people/(?P<id>\d+)/$', views.PersonController()),
    url(r'^phonenumbers/$', views.PhoneNumberController()),
    url(r'^phonetypes/$', views.get_phonetypes),
    url(r'^producttypes/$', views.ProductTypeController()),
    url(r'^producttypes/(?P<id>\d+)/$', views.ProductTypeController()),
    url(r'^products/$', views.ProductController()),
    url(r'^products/(?P<id>\d+)/$', views.ProductController()),
)
