INSERT INTO product_types(name) VALUES('ผลไม้นอก');
INSERT INTO product_types(name) VALUES('ผลไม้ไทย');
INSERT INTO product_types(name) VALUES('มะม่วง');
INSERT INTO product_types(name) VALUES('ลังมัดจำ');
INSERT INTO product_types(name) VALUES('สาลี่');
INSERT INTO product_types(name) VALUES('ส้ม');
INSERT INTO product_types(name) VALUES('องุ่น');
INSERT INTO product_types(name) VALUES('เครื่องกระป๋อง-อุปกรณ์');
INSERT INTO product_types(name) VALUES('แอปเปิ้ล');